CREATE TABLE IF NOT EXISTS Users (
  Id SERIAL PRIMARY KEY,
  Username VARCHAR(100) NOT NULL UNIQUE,
  Email VARCHAR(200),
  PasswordHash VARCHAR(510) NOT NULL,
  IsEmailVerified BOOLEAN NOT NULL DEFAULT FALSE,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  LastLogin TIMESTAMP,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS Rooms (
  Id SERIAL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  IsPrivate BOOLEAN NOT NULL DEFAULT FALSE,
  User1Id INTEGER,
  User2Id INTEGER,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  LastMessageAt TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Contacts (
  Id SERIAL PRIMARY KEY,
  UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
  ContactUserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
  Status VARCHAR(20) NOT NULL DEFAULT 'pending',
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMP,
  UNIQUE (UserId, ContactUserId)
);

CREATE TABLE IF NOT EXISTS Messages (
  Id SERIAL PRIMARY KEY,
  RoomId INTEGER NOT NULL REFERENCES Rooms(Id) ON DELETE CASCADE,
  UserId INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
  Content TEXT NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  IsRead BOOLEAN NOT NULL DEFAULT FALSE,
  IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);